### ISSUE TITLE
Account ID

### ISSUE THREAD

**Issue by shealavington** [rossdargan/monzo-hass-sensor#1]
Currently this is getting the Account_ID by the first ID inside the return from Monzo. For most of us, this will return the prepaid card. 

A simple solution to allow **current accounts** would be to select the second in the list, however this then means it's not viable for when they phase out prepaid cards or, when new people only have one account. 

_I propose making this more modular to allow people to add as many accounts as they need by setting up Monzo platform._

I managed to get my current account balance showing by changing the following which obviously isn't permanant just so I knew where it was requesting the account from:

- Old:         balance = self._client.get_balance(self._account_id) 
- **New:        balance = self._client.get_balance('acc_000xxx000xxx000xxx000')**

This means that the account can be easily passed through an extra variable in the config.

- account_id: acc_000xxx000xxx000xxx000

**Comment by rossdargan** [comment]
This has now been fixed.
