### ISSUE TITLE
Proposed Structure

### ISSUE THREAD

**Issue by shealavington** [rossdargan/monzo-hass-sensor#2]
I think it should be more modular and able to show many accounts upon request. This structure is simply an idea, even better if you can customise the Name for each one then you can set up the whole family and monitor accounts. "John Monzo", "Becky Monzo", "Barry Monzo", "Jane Monzo" all linking to their respective accounts and can be added to their own groups/views.

sensor:
  - platform: monzo
    client_id: oauthclient_XXXXXXXXXXXXXXXXXXX
    client_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    name: 'Monzo'
    accounts: 
      - acc_000xxx000xxx000xxx000 _(1)_
      - acc_111xxx111xxx000xxx000 _(2)_

This could then create a new sensor for every account shown, this should also have the "state" set to the monetary value.(Explained Below)
Sensors that should be generated upon launching Home Assistant & Potential Layout inside dev-state page.

```
- Entity: **sensor.monzo_1.balance**
- State: 25.72
- Attributes:
- - unit_of_measurement: £
- - icon: mdi:credit-card
- - friendly_name: John: Balance

- Entity: **sensor.monzo_1.spent_today**
- State: 4.20
- Attributes:
- - unit_of_measurement: £
- - icon: mdi:credit-card
- - friendly_name: John: Spent Today



- Entity: **sensor.monzo_2.balance**
- State: 5.23
- Attributes:
- - unit_of_measurement: £
- - icon: mdi:credit-card
- - friendly_name: Becky: Balance

- Entity: **sensor.monzo_2.spent_today**
- State: 2.00
- Attributes:
- - unit_of_measurement: £
- - icon: mdi:credit-card
- - friendly_name: Becky: Spent Today



- Entity: **sensor.monzo_2.transactions**
- State: 5 (How many it has generated (Max 5?))
- Attributes:
- - unit_of_measurement: transactions
- - icon: mdi:receipt
- - friendly_name: Becky: Transactions
1: Asda - £2.00 - 2016-02-05 20:12:26
1: Tesco - £12.50 - 2015-03-28 05:35:28
```
Transactions could potentially be split into their own sensor so they can be put on a card/group and then have their respective icon showing.

**Comment by shealavington** [comment]
This would need somewhat of a big rewrite. FYI.

For every account under "accounts", it should generate three new potential sensors for each one. 

- Balance, 
- Spent today, 
- Latest Transactions(Max:5).

**Comment by rossdargan** [comment]
Great idea. I'll make sure this is in before we go live.

**Comment by ghost** [comment]
Would be good to also implement pots as part of this too:
Could still use "accounts" but have a different API call dependent on the prefix:

if first 3 letters are 'acc' then use the balance api call.
if first 3 letters are 'pot' then use the pots api call.

alternatively loop through all live accounts / pots and create them all but give users to exclude (so a user could get the account / pot ID from hass rather than using the developer page.

**Comment by rossdargan** [comment]
it's a great idea. I think I should look at getting a V1 out first (I need to put a lot of the code I've added into the python library I'm using (they are happy for a PR).

Lifes got in the way, but seeing interest in the project makes me want to get back at this!

**Comment by shealavington** [comment]
Unmaintained issue board, I'm clearing out my raised but unfixed/untouched issues. Someone else is free to raise this issue again but as their own, if the issue still persists.
