### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by shealavington** [rossdargan/monzo-hass-sensor#3]
I've posted a few issues now haha! Sorry!

One of the biggest is probably cleanup, you've got a lot of dependencies and it's been pulled from so many places, I'm not sure of the source anymore, perhaps you could compile only the necessary parts into your own single git?

**Comment by rossdargan** [comment]
honestly I'm not a python dev so I'm learning as I'm going with this - hopefully someone can give me a hand with this, if not I'll see what I can find!

**Comment by shealavington** [comment]
Unmaintained issue board, I'm clearing out my raised but unfixed/untouched issues. Someone else is free to raise this issue again but as their own, if the issue still persists.
