### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by shealavington** [rossdargan/monzo-hass-sensor#4]
As stated in the Home Assistant discussion, there's a lot of hit and miss with the authentication. Putting it here so you can track the issue :P

**Comment by rossdargan** [comment]
Yeah, I need to look into this.

**Comment by ghost** [comment]
Submitted a PR to fix one issue with authentication (out of date url being used)

**Comment by rossdargan** [comment]
Thanks @Pow377. Hopefulyl this was the cause of the authentication issues. Lets see if anyone else adds a comment

**Comment by shealavington** [comment]
Unmaintained issue board, I'm clearing out my raised but unfixed/untouched issues. Someone else is free to raise this issue again but as their own, if the issue still persists.
