### ISSUE TITLE
No Balance Refresh/Update

### ISSUE THREAD

**Issue by shealavington** [rossdargan/monzo-hass-sensor#5]
I Had someone deposit £30 into my account this morning however there's no balance update on Home Assistant - My balance showing in Home Assistant is the same as when I restarted Home Assistant last night.

Restarted Home Assistant - Back to configuration screen? I'm at work so I'll have a look when I'm home to try and see why this is.

**Comment by rossdargan** [comment]
Is this still an issue for you?

**Comment by shealavington** [comment]
Unmaintained issue board, I'm clearing out my raised but unfixed/untouched issues. Someone else is free to raise this issue again but as their own, if the issue still persists.
